version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: audit_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audit_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8
    container_name: audit_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: audit_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: audit_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: audit_test
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/audit_test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

